"""
This is just a list of API resource constants. If you add some, keep it in
alphabetical order.
"""

ARCHIVE = "Archive"
ARCHIVE_METADATA = "ArchiveMetadata"
AUTH_TOKEN = "AuthToken"
CLI = "cli"
COMPUTER = "Computer"
COMPUTER_BLOCK = "ComputerBlock"
COMPUTER_DEACTIVATION = "ComputerDeactivation"
DATA_KEY_TOKEN = "DataKeyToken"
DESTINATION = "Destination"
DEVICE_UPGRADE = "DeviceUpgrade"
FILE_CONTENT = "FileContent"
FILE_METADATA = "FileMetadata"
LOGIN_TOKEN = "LoginToken"
NETWORK_TEST = "NetworkTest"
ORG = "Org"
PING = "Ping"
PLAN = "Plan"
PUSH_RESTORE_JOB = "PushRestoreJob"
RESTORE_RECORD = "RestoreRecord"
SECURITY_DETECTION_EVENTS = "SecurityDetectionEvents"
SERVER = "Server"
STORAGE = "Storage"
STORAGE_AUTH_TOKEN = "StorageAuthToken"
STORE_POINT = "StorePoint"
USER = "User"
USER_DEACTIVATION = "UserDeactivation"
USER_MOVE_PROCESS = "UserMoveProcess"
USER_ROLE = "UserRole"
WEB_RESTORE_JOB = "WebRestoreJob"
WEB_RESTORE_JOB_RESULT = "WebRestoreJobResult"
WEB_RESTORE_SEARCH = "WebRestoreSearch"
WEB_RESTORE_SESSION = "WebRestoreSession"
